version: '2'
services:
  users-service:
    container_name: users-service
    build: ./services/users/
    volumes:
      - './services/users:/usr/src/app'
      - './services/users/package.json:/usr/src/package.json'
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgres://admin:admin@users-db:5433/users_dev
      - DATABASE_TEST_URL=postgres://admin:admin@users-db:5433/users_test
      - NODE_ENV=development
    depends_on:
      - users-db
    links:
      - users-db
  mockups-service:
    container_name: mockups-service
    build: ./services/mockups/
    volumes:
      - './services/mockups:/usr/src/app'
      - './services/mockups/package.json:/usr/src/package.json'
    ports:
      - '8081:8080'
    env_file: .env
    environment:
      - DATABASE_URL=postgres://admin:admin@mockups-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://admin:admin@mockups-db:5432/users_test
      - NODE_ENV=development
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    depends_on:
      - mockups-db
    links:
      - mockups-db
  users-db:
    container_name: users-db
    build: ./services/users/src/db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  mockups-db:
    container_name: mockups-db
    build: ./services/mockups/src/db
    ports:
      - '27017:27017'
  web-service:
    container_name: web-service
    build: ./web/
    volumes:
      - './web:/usr/src'
      - '/usr/src/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - users-service
      - mockups-service
    links:
      - users-service
      - mockups-service
